-module(maislurp-client-erlang_email_projection).

-export([encode/1]).

-export_type([maislurp-client-erlang_email_projection/0]).

-type maislurp-client-erlang_email_projection() ::
    #{ 'subject' => binary(),
       'sizeBytes' => integer(),
       'messageId' => binary(),
       'favourite' => boolean(),
       'domainId' => maislurp-client-erlang_u_uid:maislurp-client-erlang_u_uid(),
       'attachments' => list(),
       'inboxId' := maislurp-client-erlang_u_uid:maislurp-client-erlang_u_uid(),
       'createdAt' := maislurp-client-erlang_date_time:maislurp-client-erlang_date_time(),
       'to' := list(),
       'cc' => list(),
       'bcc' => list(),
       'sender' => maislurp-client-erlang_sender:maislurp-client-erlang_sender(),
       'recipients' => maislurp-client-erlang_email_recipients:maislurp-client-erlang_email_recipients(),
       'plusAddress' => maislurp-client-erlang_u_uid:maislurp-client-erlang_u_uid(),
       'imapUid' => integer(),
       'inReplyTo' => binary(),
       'read' := boolean(),
       'bodyExcerpt' => binary(),
       'textExcerpt' => binary(),
       'bodyPartContentTypes' => list(),
       'bodyMD5Hash' => binary(),
       'teamAccess' := boolean(),
       'id' := maislurp-client-erlang_u_uid:maislurp-client-erlang_u_uid(),
       'threadId' => maislurp-client-erlang_u_uid:maislurp-client-erlang_u_uid(),
       'from' := binary()
     }.

encode(#{ 'subject' := Subject,
          'sizeBytes' := SizeBytes,
          'messageId' := MessageId,
          'favourite' := Favourite,
          'domainId' := DomainId,
          'attachments' := Attachments,
          'inboxId' := InboxId,
          'createdAt' := CreatedAt,
          'to' := To,
          'cc' := Cc,
          'bcc' := Bcc,
          'sender' := Sender,
          'recipients' := Recipients,
          'plusAddress' := PlusAddress,
          'imapUid' := ImapUid,
          'inReplyTo' := InReplyTo,
          'read' := Read,
          'bodyExcerpt' := BodyExcerpt,
          'textExcerpt' := TextExcerpt,
          'bodyPartContentTypes' := BodyPartContentTypes,
          'bodyMD5Hash' := BodyMD5Hash,
          'teamAccess' := TeamAccess,
          'id' := Id,
          'threadId' := ThreadId,
          'from' := From
        }) ->
    #{ 'subject' => Subject,
       'sizeBytes' => SizeBytes,
       'messageId' => MessageId,
       'favourite' => Favourite,
       'domainId' => DomainId,
       'attachments' => Attachments,
       'inboxId' => InboxId,
       'createdAt' => CreatedAt,
       'to' => To,
       'cc' => Cc,
       'bcc' => Bcc,
       'sender' => Sender,
       'recipients' => Recipients,
       'plusAddress' => PlusAddress,
       'imapUid' => ImapUid,
       'inReplyTo' => InReplyTo,
       'read' => Read,
       'bodyExcerpt' => BodyExcerpt,
       'textExcerpt' => TextExcerpt,
       'bodyPartContentTypes' => BodyPartContentTypes,
       'bodyMD5Hash' => BodyMD5Hash,
       'teamAccess' => TeamAccess,
       'id' => Id,
       'threadId' => ThreadId,
       'from' => From
     }.
