-module(maislurp-client-erlang_campaign_probe_run_dto).

-export([encode/1]).

-export_type([maislurp-client-erlang_campaign_probe_run_dto/0]).

-type maislurp-client-erlang_campaign_probe_run_dto() ::
    #{ 'id' := maislurp-client-erlang_u_uid:maislurp-client-erlang_u_uid(),
       'probeId' := maislurp-client-erlang_u_uid:maislurp-client-erlang_u_uid(),
       'userId' := maislurp-client-erlang_u_uid:maislurp-client-erlang_u_uid(),
       'status' := binary(),
       'source' := binary(),
       'healthScore' := integer(),
       'totalChecks' := integer(),
       'passingChecks' := integer(),
       'failingChecks' := integer(),
       'checkedLinks' := integer(),
       'checkedImages' := integer(),
       'linkIssueCount' := integer(),
       'imageIssueCount' := integer(),
       'compatibilityWarningCount' := integer(),
       'compatibilityNotSupportedCount' := integer(),
       'compatibilityUnknownCount' := integer(),
       'htmlErrorCount' := integer(),
       'htmlWarningCount' := integer(),
       'htmlInfoCount' := integer(),
       'reputationFailureCount' := integer(),
       'attachmentMentionIssueCount' := integer(),
       'insights' := list(),
       'errorMessage' => binary(),
       'fromAddress' => binary(),
       'recipient' => binary(),
       'subject' => binary(),
       'messageId' => binary(),
       'sourceMessageId' => binary(),
       'processingMs' => integer(),
       'createdAt' := maislurp-client-erlang_date_time:maislurp-client-erlang_date_time(),
       'updatedAt' := maislurp-client-erlang_date_time:maislurp-client-erlang_date_time()
     }.

encode(#{ 'id' := Id,
          'probeId' := ProbeId,
          'userId' := UserId,
          'status' := Status,
          'source' := Source,
          'healthScore' := HealthScore,
          'totalChecks' := TotalChecks,
          'passingChecks' := PassingChecks,
          'failingChecks' := FailingChecks,
          'checkedLinks' := CheckedLinks,
          'checkedImages' := CheckedImages,
          'linkIssueCount' := LinkIssueCount,
          'imageIssueCount' := ImageIssueCount,
          'compatibilityWarningCount' := CompatibilityWarningCount,
          'compatibilityNotSupportedCount' := CompatibilityNotSupportedCount,
          'compatibilityUnknownCount' := CompatibilityUnknownCount,
          'htmlErrorCount' := HtmlErrorCount,
          'htmlWarningCount' := HtmlWarningCount,
          'htmlInfoCount' := HtmlInfoCount,
          'reputationFailureCount' := ReputationFailureCount,
          'attachmentMentionIssueCount' := AttachmentMentionIssueCount,
          'insights' := Insights,
          'errorMessage' := ErrorMessage,
          'fromAddress' := FromAddress,
          'recipient' := Recipient,
          'subject' := Subject,
          'messageId' := MessageId,
          'sourceMessageId' := SourceMessageId,
          'processingMs' := ProcessingMs,
          'createdAt' := CreatedAt,
          'updatedAt' := UpdatedAt
        }) ->
    #{ 'id' => Id,
       'probeId' => ProbeId,
       'userId' => UserId,
       'status' => Status,
       'source' => Source,
       'healthScore' => HealthScore,
       'totalChecks' => TotalChecks,
       'passingChecks' => PassingChecks,
       'failingChecks' => FailingChecks,
       'checkedLinks' => CheckedLinks,
       'checkedImages' => CheckedImages,
       'linkIssueCount' => LinkIssueCount,
       'imageIssueCount' => ImageIssueCount,
       'compatibilityWarningCount' => CompatibilityWarningCount,
       'compatibilityNotSupportedCount' => CompatibilityNotSupportedCount,
       'compatibilityUnknownCount' => CompatibilityUnknownCount,
       'htmlErrorCount' => HtmlErrorCount,
       'htmlWarningCount' => HtmlWarningCount,
       'htmlInfoCount' => HtmlInfoCount,
       'reputationFailureCount' => ReputationFailureCount,
       'attachmentMentionIssueCount' => AttachmentMentionIssueCount,
       'insights' => Insights,
       'errorMessage' => ErrorMessage,
       'fromAddress' => FromAddress,
       'recipient' => Recipient,
       'subject' => Subject,
       'messageId' => MessageId,
       'sourceMessageId' => SourceMessageId,
       'processingMs' => ProcessingMs,
       'createdAt' => CreatedAt,
       'updatedAt' => UpdatedAt
     }.
