-module(maislurp-client-erlang_deliverability_test_dto).

-export([encode/1]).

-export_type([maislurp-client-erlang_deliverability_test_dto/0]).

-type maislurp-client-erlang_deliverability_test_dto() ::
    #{ 'id' := maislurp-client-erlang_u_uid:maislurp-client-erlang_u_uid(),
       'name' => binary(),
       'description' => binary(),
       'scope' := binary(),
       'selector' := maislurp-client-erlang_deliverability_selector_options:maislurp-client-erlang_deliverability_selector_options(),
       'selectedEntityCount' := integer(),
       'expectations' := list(),
       'status' := binary(),
       'startAt' := maislurp-client-erlang_date_time:maislurp-client-erlang_date_time(),
       'startedAt' => maislurp-client-erlang_date_time:maislurp-client-erlang_date_time(),
       'completedAt' => maislurp-client-erlang_date_time:maislurp-client-erlang_date_time(),
       'maxDurationSeconds' => integer(),
       'successThresholdPercent' => float(),
       'thresholdStatus' := binary(),
       'thresholdMet' => boolean(),
       'lastEvaluatedAt' => maislurp-client-erlang_date_time:maislurp-client-erlang_date_time(),
       'totalEntities' := integer(),
       'matchedEntities' := integer(),
       'unmatchedEntities' := integer(),
       'completionPercentage' := float(),
       'timedOut' := boolean(),
       'failureReason' => binary(),
       'createdAt' := maislurp-client-erlang_date_time:maislurp-client-erlang_date_time(),
       'updatedAt' := maislurp-client-erlang_date_time:maislurp-client-erlang_date_time()
     }.

encode(#{ 'id' := Id,
          'name' := Name,
          'description' := Description,
          'scope' := Scope,
          'selector' := Selector,
          'selectedEntityCount' := SelectedEntityCount,
          'expectations' := Expectations,
          'status' := Status,
          'startAt' := StartAt,
          'startedAt' := StartedAt,
          'completedAt' := CompletedAt,
          'maxDurationSeconds' := MaxDurationSeconds,
          'successThresholdPercent' := SuccessThresholdPercent,
          'thresholdStatus' := ThresholdStatus,
          'thresholdMet' := ThresholdMet,
          'lastEvaluatedAt' := LastEvaluatedAt,
          'totalEntities' := TotalEntities,
          'matchedEntities' := MatchedEntities,
          'unmatchedEntities' := UnmatchedEntities,
          'completionPercentage' := CompletionPercentage,
          'timedOut' := TimedOut,
          'failureReason' := FailureReason,
          'createdAt' := CreatedAt,
          'updatedAt' := UpdatedAt
        }) ->
    #{ 'id' => Id,
       'name' => Name,
       'description' => Description,
       'scope' => Scope,
       'selector' => Selector,
       'selectedEntityCount' => SelectedEntityCount,
       'expectations' => Expectations,
       'status' => Status,
       'startAt' => StartAt,
       'startedAt' => StartedAt,
       'completedAt' => CompletedAt,
       'maxDurationSeconds' => MaxDurationSeconds,
       'successThresholdPercent' => SuccessThresholdPercent,
       'thresholdStatus' => ThresholdStatus,
       'thresholdMet' => ThresholdMet,
       'lastEvaluatedAt' => LastEvaluatedAt,
       'totalEntities' => TotalEntities,
       'matchedEntities' => MatchedEntities,
       'unmatchedEntities' => UnmatchedEntities,
       'completionPercentage' => CompletionPercentage,
       'timedOut' => TimedOut,
       'failureReason' => FailureReason,
       'createdAt' => CreatedAt,
       'updatedAt' => UpdatedAt
     }.
